language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r tests/requirements.txt
- pip install -r requirements.txt
- python setup.py install
script:
- python setup.py check -rms
- flake8
- pytest
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  skip_existing: true
  skip_cleanup: true
  user: __token__
  on:
    tags: true
    branch: master
  password:
    secure: EtotYlyTesfh6p+ln9nWtUB5eHMJQbTCqfxXZuji9FqzQ0gmrrSsuDMAKLD7wpErRJvDbD9FgE9GpmGBzq/nB2P8YAMT+cfdw1MTKy//mCPpImKjiMHccLDayEbOn3OEoFOe42SelYzX9GWenZQTAJKkPzBL3W/C7jTzp4LOjXOvm2TLVuc2dLpv/pVbHO47kL8/slpYbNMOwthQ1kWWFtz5OtO6BNKf/1/1q8EX0z2oRPMc+Fn/09amtzhoTmMp8Kg/geqSTbrgBrCJ5X8sYvMMBh7t0L38hDEfMHtS6tM3TymndJ2JaXIlR+rvnGvcInVHBQCxltNSmNqWZnXx8Qj+BdRHWXIHuYSwmgDC5Lh9BRmUkTfkPtnT+KAk/YeBiIFfVhmd1lS/n3J999/E0mYnd4Q0pWp8BHzF0oQ6XUzoiPVAK9jYULqq2lyvOYitYTEFjP5cFVZY+S4Eo6bD1wSi2z/kBiGqXObjbimuBFYOrq8dNMA6B2uqnlnhoJ5nV8GGW1ph5/o8kfwWevb9NKk/2TazPdTk8BDp1+tteYgejUuz9sSKtwVZCiS/8nUW8iOJ4D8Utu685ofRhpecoBkUIQl1G9Fa1S+m58RFfVd6M/f2T13g3x9nNiK11n0y7q8JFt1iB27FDxM9a6hYoF97SdKyuu2TE20/pldm0+8=
