version: '3.7'

# Only use this stack for development or debugging,
# A WSGI stack should be used for production (docker-compose.yml)
services:
  web:
    image: nielsbohr/projects-site:edge
    container_name: projects
    environment:
      FLASK_DEBUG: 1
    ports:
      - "80:80/tcp"
    volumes:
      - ./persistence:/var/projects/persistence:rw
      - ./res/config.ini:/var/projects/res/config.ini:ro
      - ./res/projects-envvars.py:/etc/projects/projects-envvars.py:ro
    command: python3 /var/projects/run.py --debug --port 80
